export type SupportedIndex = 'NIFTY' | 'BANK NIFTY' | 'SENSEX';

export interface StrikeData {
  strikePrice: number;
  ceOI: number;
  peOI: number;
  cePreviousOI?: number;
  pePreviousOI?: number;
  ceOIChange?: number;
  peOIChange?: number;
  ceSecurityId?: number;
  peSecurityId?: number;
  ceLTP?: number;
  peLTP?: number;
  ceVolume?: number;
  peVolume?: number;
}

export interface OIChangeResult {
  ceOIChange: number;
  peOIChange: number;
  ceOIChangePct: number;
  peOIChangePct: number;
}

export interface OISnapshotData {
  timestamp: string | Date;
  totalCallOI: number;
  totalPutOI: number;
  strikes?: StrikeData[];
}


export interface NormalizedOptionChain {
  index: SupportedIndex;
  timestamp: string; // ISO string generated by backend
  dateStr: string; // "YYYY-MM-DD"
  timeStr: string; // "HH:MM AM/PM"
  expiry: string; // "YYYY-MM-DD"
  underlyingValue?: number;
  totalCallOI: number;
  totalPutOI: number;
  strikes: StrikeData[];
}

/**
 * Raw Dhan Option Chain API response structure based on Dhan API v2 docs:
 * POST /v2/optionchain
 */
export interface RawDhanOptionChain {
  status?: string;
  remarks?: string;
  data?: {
    last_price?: number;
    oc?: Record<string, {
      ce?: {
        oi?: number;
        previous_oi?: number;
        security_id?: number;
        last_price?: number;
        volume?: number;
        [key: string]: unknown;
      };
      pe?: {
        oi?: number;
        previous_oi?: number;
        security_id?: number;
        last_price?: number;
        volume?: number;
        [key: string]: unknown;
      };
      [key: string]: unknown;
    }>;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/**
 * Raw Dhan Expiry List API response structure:
 * POST /v2/optionchain/expirylist
 */
export interface RawDhanExpiryList {
  status?: string;
  remarks?: string;
  data?: string[];
  [key: string]: unknown;
}

/**
 * Raw Upstox Option Chain Market Data structure
 */
export interface UpstoxMarketData {
  ltp?: number;
  volume?: number;
  oi?: number;
  close_price?: number;
  bid_price?: number;
  bid_qty?: number;
  ask_price?: number;
  ask_qty?: number;
  prev_oi?: number;
  [key: string]: unknown;
}

export interface UpstoxOptionDetail {
  instrument_key?: string;
  market_data?: UpstoxMarketData;
  option_greeks?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface RawUpstoxOptionItem {
  expiry?: string;
  pcr?: number;
  strike_price?: number;
  underlying_key?: string;
  underlying_spot_price?: number;
  call_options?: UpstoxOptionDetail;
  put_options?: UpstoxOptionDetail;
  [key: string]: unknown;
}

/**
 * Raw Upstox Option Chain API response structure:
 * GET /v2/option/chain
 */
export interface RawUpstoxOptionChain {
  status?: string;
  data?: RawUpstoxOptionItem[];
  errors?: Array<{ errorCode?: string; message?: string; propertyPath?: string }>;
  [key: string]: unknown;
}

export interface RawUpstoxContractItem {
  expiry?: string;
  strike_price?: number;
  instrument_key?: string;
  instrument_type?: string;
  [key: string]: unknown;
}

/**
 * Raw Upstox Option Contracts API response structure:
 * GET /v2/option/contract
 */
export interface RawUpstoxContractsResponse {
  status?: string;
  data?: RawUpstoxContractItem[] | string[];
  errors?: Array<{ errorCode?: string; message?: string; propertyPath?: string }>;
  [key: string]: unknown;
}

export interface StrikeDetail {
  strikePrice: number;
  isATM: boolean;
  isCallOTM: boolean;
  isPutOTM: boolean;
  ceOI: number;
  peOI: number;
  cePreviousOI?: number;
  pePreviousOI?: number;
  ceOIChange?: number;
  peOIChange?: number;
  ceOIChangePct?: number;
  peOIChangePct?: number;
  ceLTP?: number;
  peLTP?: number;
  ceVolume?: number;
  peVolume?: number;
}

export interface ATMPlus4OTMResult {
  spotPrice: number;
  atmStrike: number;
  strikeSpacing: number;
  callStrikes: number[];
  putStrikes: number[];
  relevantStrikes: number[];
  strikeDetails: StrikeDetail[];
  totalCallOI: number;
  totalPutOI: number;
  prevDayCloseCallOI: number;
  prevDayClosePutOI: number;
  callOIChangeVal: number;
  callOIChangePct: number;
  putOIChangeVal: number;
  putOIChangePct: number;
  pcr: number;
}

export interface OIRow {
  time: string;
  spotPrice?: number;
  atmStrike?: number;
  callOI: number;
  putOI: number;
  pcr?: number;
  // SECTION 2: OPEN INTEREST CHANGE (OI CHANGE)
  callOIChange: number;
  putOIChange: number;
  callDifference: number | null;
  putDifference: number | null;
  // Legacy/Alias properties
  snapshotCallDiff?: number;
  snapshotPutDiff?: number;
  fullDayCallChangeVal?: number;
  fullDayCallChangePct?: number;
  fullDayPutChangeVal?: number;
  fullDayPutChangePct?: number;
  callChangeVal?: number;
  callChangePct?: number;
  putChangeVal?: number;
  putChangePct?: number;
  isHighlighted?: boolean;
}

export interface SummaryMetrics {
  startTime: string;
  endTime: string;
  currentExpiry?: string;
  spotPrice?: number;
  atmStrike?: number;
  pcr?: number;
  prevDayCloseCallOI?: number;
  prevDayClosePutOI?: number;
  startCallOI: number;
  startPutOI: number;
  endCallOI: number;
  endPutOI: number;
  callOIChangeVal: number;
  callOIChangePct: number;
  putOIChangeVal: number;
  putOIChangePct: number;
  interimTime?: string;
  interimCallOIChangeVal?: number;
  interimCallOIChangePct?: number;
  interimPutOIChangeVal?: number;
  interimPutOIChangePct?: number;
}

export interface IndexDataset {
  index: SupportedIndex;
  currentExpiry?: string;
  spotPrice?: number;
  atmStrike?: number;
  pcr?: number;
  availableDates: string[];
  selectedDate: string;
  timeOptions: string[];
  summary: SummaryMetrics;
  rows: OIRow[];
  strikeDetails?: StrikeDetail[];
}

export interface OptionChainApiResponse<T = unknown> {
  success: boolean;
  status: 'ok' | 'pending_configuration' | 'error';
  message?: string;
  configured: boolean;
  dbConnected: boolean;
  data: T | null;
  timestamp: string;
}

