export type SupportedIndex = 'NIFTY' | 'BANK NIFTY' | 'SENSEX';

export interface StrikeData {
  strikePrice: number;
  ceOI: number;
  peOI: number;
  cePreviousOI?: number;
  pePreviousOI?: number;
  ceSecurityId?: number;
  peSecurityId?: number;
  ceLTP?: number;
  peLTP?: number;
  ceVolume?: number;
  peVolume?: number;
}

export interface NormalizedOptionChain {
  index: SupportedIndex;
  timestamp: string; // ISO string generated by backend
  dateStr: string; // "YYYY-MM-DD"
  timeStr: string; // "HH:MM AM/PM"
  expiry: string; // "YYYY-MM-DD"
  underlyingValue?: number;
  totalCallOI: number;
  totalPutOI: number;
  strikes: StrikeData[];
}

/**
 * Raw Dhan Option Chain API response structure based on Dhan API v2 docs:
 * POST /v2/optionchain
 */
export interface RawDhanOptionChain {
  status?: string;
  remarks?: string;
  data?: {
    last_price?: number;
    oc?: Record<string, {
      ce?: {
        oi?: number;
        previous_oi?: number;
        security_id?: number;
        last_price?: number;
        volume?: number;
        [key: string]: unknown;
      };
      pe?: {
        oi?: number;
        previous_oi?: number;
        security_id?: number;
        last_price?: number;
        volume?: number;
        [key: string]: unknown;
      };
      [key: string]: unknown;
    }>;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/**
 * Raw Dhan Expiry List API response structure:
 * POST /v2/optionchain/expirylist
 */
export interface RawDhanExpiryList {
  status?: string;
  remarks?: string;
  data?: string[];
  [key: string]: unknown;
}

export interface OIRow {
  time: string;
  callOI: number;
  putOI: number;
  callChangeVal: number;
  callChangePct: number;
  putChangeVal: number;
  putChangePct: number;
  isHighlighted?: boolean;
}

export interface SummaryMetrics {
  startTime: string;
  endTime: string;
  startCallOI: number;
  startPutOI: number;
  endCallOI: number;
  endPutOI: number;
  callOIChangeVal: number;
  callOIChangePct: number;
  putOIChangeVal: number;
  putOIChangePct: number;
  interimTime?: string;
  interimCallOIChangeVal?: number;
  interimCallOIChangePct?: number;
  interimPutOIChangeVal?: number;
  interimPutOIChangePct?: number;
}

export interface IndexDataset {
  index: SupportedIndex;
  availableDates: string[];
  selectedDate: string;
  timeOptions: string[];
  summary: SummaryMetrics;
  rows: OIRow[];
}

export interface OptionChainApiResponse<T = unknown> {
  success: boolean;
  status: 'ok' | 'pending_configuration' | 'error';
  message?: string;
  configured: boolean;
  dbConnected: boolean;
  data: T | null;
  timestamp: string;
}
